package ca.cours5b5.justinfofana.global;

public enum GCommande {
    CHOISIR_HAUTEUR,
    CHOISIR_LARGEUR,
    CHOISIR_POUR_GAGNER,
    EFFACER_MODELE,

    DEMARRER_PARTIE,
    OUVRIR_MENU_PARAMETRES,
    CONNEXION,
    DECONNEXION,

    JOUER_COUP_ICI,
    COULEUR_JOUEUR
}
